### ISSUE TITLE
create job with processors

### ISSUE THREAD

**Issue by carl10086** [distribworks/dkron#1033]
**Describe the bug**

When a create a job with processors use `curl`.

**To Reproduce**

```
{
	"name": "job1",
	"schedule": "@every 10s",
	"timezone": "Asia/Shanghai",
	"disabled": false,
	"processors": {
		"files": {
		   "log_dir": "/log0/dkron/job1",
		   "forward": true
		}
	},
	"concurrency": "allow",
	"executor": "shell",
	"executor_config": {
		"command": "/home/admin/test.sh"
	}
}
```

**Expected behavior**

create successful .

**Screenshots**

`Unable to parse payload: json: cannot unmarshal bool into Go struct field Job.processors of type string.`

** Specifications:**
 - OS: mac

**Additional context**
without forward . it's success .

when i change from :

`"forward":true` to `"forward":"true"` it's ok .

**Comment by yvanoers** [comment]
This is by design. It is also [documented](https://dkron.io/usage/processors/file/) to be specified as a string.
Any values passed into a processor or executor plugin configuration need to be strings. The reason being that this (easily) allows plugins to accept any configuration they might need, without dkron needing to know beforehand what that would be.
Making the plugin interface use the appropriate types would probably make it a tedious task to create plugins.

**Comment by vcastellm** [comment]
Duplicate of #1034
