### ISSUE TITLE
Build and release process problem

### ISSUE THREAD

**Issue by Demonian** [distribworks/dkron#585]
Use this template if you are reporting a bug. Don't use this template of you are proposing a feature.

## Expected Behavior
**Problem 1**
Image of the latest version should be pushed to Docker Hub. Current latest version is `v2.0.0-b7` but it is missing. The latest version in Docker Hub is `v2.0.0-b6` [Link to Docker Hub](https://hub.docker.com/r/dkron/dkron/tags?page=1)
**Problem 2**
It seems that the shell executor is missing inside the docker image, according to the output of this command `docker run --entrypoint "/bin/ls" dkron/dkron:latest /opt/local/dkron`:
```
dkron
dkron-executor-http
dkron-processor-files
dkron-processor-log
dkron-processor-syslog
```

## Actual Behavior
**Problem 1**
Latest version is pushed to Docker Hub.
**Problem 2**
All builtin executors should be inside the image.

**Comment by victorcoder** [comment]
Hey @Demonian, thanks for checking that, the release changes between b6 and b7 due to an important upgrade in Goreleaser, this fixes the problem of the missing shell executor: https://github.com/distribworks/dkron/commit/be6c33c1ee86f7984d57040b43d5a4c45d04b39a 

Regarding b7 missing in dockerhub was an issue with the upload from my computer.

I'm going to remove b7 release and just continue with b8

**Comment by Demonian** [comment]
@victorcoder Thanks for the description=)
