### ISSUE TITLE
Unexpected update of next execution time

### ISSUE THREAD

**Issue by omerl13** [distribworks/dkron#598]
The Next Exec. time is getting updated unexpectedly in the following scenario:
1. Creating a job
2. Restarting dkron
3. Running the job manually via UI

After these actions, the next execution time is updated. But after running manually again, the next exec time is not updated. 

I am not sure whether next exec time should be modified after manual run or not, but it should behave the same. 

Tested in v2.0.0-rc3

**Comment by victorcoder** [comment]
This is the expected behavior @omerl13, the manual run just start the job in that instant but don't modify the next run time. The job will run when it is scheduled.

The next execution time is bound to the job schedule and should not be modified by a manual run, specially with fixed cron expressions.
