### ISSUE TITLE
Add node name to tags as a reserved tag

### ISSUE THREAD

**Issue by aaronjheng** [distribworks/dkron#663]
**Is your feature request related to a problem? Please describe.**
I want to run a job in a specific node. For now, I can only use a "node" tag with hostname or unique name to get that.

**Describe the solution you'd like**
Add node name to tags as a reserved tag.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by yvanoers** [comment]
Hi @aaronjheng,
Would you mind elaborating on your use case?
I can see why including the hostname as one of the tags may be useful, but they are not always stable (e.g. with docker). Also I'm curious what the one host is supposed to do: Dkron's purpose is to make scheduling scale and/or highly available. Targeting a specific host is exactly the opposite. 

Please enlighten us!

**Comment by aaronjheng** [comment]
We have plenty of cron jobs. These jobs may only live in a single host. For me, these hosts are stable (they are not in containers). So I need to target a specific.

**Comment by yvanoers** [comment]
@aaronjheng 
Can you explain why those jobs only allowed to live on a single host?

**Comment by aaronjheng** [comment]
Sorry for the late response. We only have one server for these jobs for now. I think hostname is a good choice for targetting. So I add a tag named "host" manually. Making it reserved will be useful. Even in containers, we can just skip "host" and use other tags for good if we have to.

**Comment by aaronjheng** [comment]
I understand scalability is important. If you guys think the "hostname" thing is not good, I can just use a explicit tag.

**Comment by yvanoers** [comment]
@aaronjheng 
I suspect you're trying to solve a non-existent problem. Or I don't understand what the problem is :)

Based on your situation as I understand it, I can think of the following scenarios and targeting strategies:
- Only one server:<br>there's no need to target jobs, they'll just run on all (so, just one) available agents in the cluster.
- Multiple servers, each having to run their own jobs locally (no HA or failover):<br>Run all servers as their own cluster: no need to target jobs.
- Only one server now, maybe more in the future, a job has to run on only one of all servers:<br>Target a job to `"role":":1"`, and it will run on _one_ of the agents in the cluster.

As I see it, using a hostname as a tag will only create more work for you if at some point in the future you have to:
- move a job to another server
- rename the host
- run a job with failover in mind

The only reason I can think of where a hostname tag might be useful, is if a job is meant to address one server specifically. For example, some maintenance script that needs to run in order for the machine to keep running properly. In that case though, IMHO, the job should be run by crond (or equivalent local scheduler), because it is tied to that machine.

> If you guys think the "hostname" thing is not good

The 'why' is important. I don't see what problem this solves, but that doesn't mean there isn't one.
I try to help guide how you use Dkron to get the most out of it. And if a useful feature is missing, I will gladly submit a PR to implement it.

Does any of the above scenarios apply to you?

**Comment by aaronjheng** [comment]
@yvanoers Thanks for your explanations. I think I should just use tags.
